# Generated by Django 4.0.6 on 2022-08-11 12:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone in format xxx xxx xxxx', regex='^(\\d{3}[- .]?){2}\\d{4}$')])),
                ('person', models.PositiveSmallIntegerField()),
                ('message', models.TextField(blank=True, max_length=400)),
                ('plan_date', models.DateField(blank=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('in_processed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-date', '-in_processed'),
            },
        ),
        migrations.AlterModelOptions(
            name='whytus',
            options={},
        ),
        migrations.RenameField(
            model_name='aboutus',
            old_name='itle',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='whytus',
            name='is_visible',
        ),
        migrations.AddField(
            model_name='galery',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Spesial',
        ),
    ]
